#!/bin/bash

echo "Installing vscode extensions"
code --install-extension alefragnani.Bookmarks
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension castwide.solargraph
code --install-extension christian-kohler.npm-intellisense
code --install-extension cmstead.jsrefactor
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension hashicorp.terraform
code --install-extension jebbs.plantuml
code --install-extension karunamurti.haml
code --install-extension mathiasfrohlich.Kotlin
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension oderwat.indent-rainbow
code --install-extension Orta.vscode-jest
code --install-extension rarnoldmobile.todo-txt
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension remimarsal.prettier-now
code --install-extension sianglim.slim
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension wingrunr21.vscode-ruby
code --install-extension wwm.better-align
